package com.vikingsai.engine.tick

import com.vikingsai.common.model.*
import com.vikingsai.engine.world.MutableEntity
import com.vikingsai.engine.world.WorldManager
import org.slf4j.LoggerFactory

/**
 * Validates and applies agent actions to the world state.
 * Returns a list of world events generated by the actions.
 */
class ActionResolver(private val world: WorldManager) {

    private val log = LoggerFactory.getLogger(ActionResolver::class.java)

    fun resolve(action: AgentAction): List<WorldEvent> {
        val agent = world.agents.find { it.name == action.agentName }
        if (agent == null) {
            log.warn("Action from unknown agent: ${action.agentName}")
            return emptyList()
        }
        if (agent.status == AgentStatus.DEAD) return emptyList()

        return when (action.action) {
            ActionType.MOVE -> resolveMove(agent, action)
            ActionType.GATHER -> resolveGather(agent, action)
            ActionType.FIGHT -> resolveFight(agent, action)
            ActionType.BUILD -> resolveBuild(agent, action)
            ActionType.PATROL -> resolvePatrol(agent, action)
            ActionType.FLEE -> resolveFlee(agent, action)
            ActionType.SPEAK -> resolveSpeak(agent, action)
            ActionType.IDLE -> {
                agent.currentAction = ActionType.IDLE
                agent.currentDirection = null
                emptyList()
            }
        }
    }

    private fun resolveMove(
        agent: com.vikingsai.engine.world.MutableAgent,
        action: AgentAction
    ): List<WorldEvent> {
        val direction = action.direction ?: return emptyList()
        world.moveAgent(agent, direction)
        agent.currentAction = ActionType.MOVE
        agent.currentDirection = direction
        return emptyList()
    }

    private fun resolveGather(
        agent: com.vikingsai.engine.world.MutableAgent,
        action: AgentAction
    ): List<WorldEvent> {
        agent.currentAction = ActionType.GATHER
        agent.currentDirection = null
        val resource = world.tryGather(agent) ?: return emptyList()
        return listOf(WorldEvent(
            tick = world.tick,
            eventType = EventType.RESOURCE_GATHERED,
            description = "${agent.name} gathered ${resource.name.lowercase()}",
            severity = Severity.LOW,
            affectedPositions = listOf(agent.position)
        ))
    }

    private fun resolveFight(
        agent: com.vikingsai.engine.world.MutableAgent,
        action: AgentAction
    ): List<WorldEvent> {
        // Find nearest threat to fight
        val target = world.entities
            .filter { it.type == EntityType.WOLF || it.type == EntityType.DRAGON }
            .minByOrNull { manhattanDist(agent.position, it.position) }
            ?: return emptyList()

        agent.currentAction = ActionType.FIGHT

        if (manhattanDist(agent.position, target.position) > 1) {
            // Move toward target instead
            agent.currentDirection = moveToward(agent, target.position)
            return emptyList()
        }

        val killed = world.resolveCombat(agent, target)
        val events = mutableListOf<WorldEvent>()

        events.add(WorldEvent(
            tick = world.tick,
            eventType = EventType.COMBAT,
            description = "${agent.name} fights a ${target.type.name.lowercase()}! (HP: ${agent.health})",
            severity = if (target.type == EntityType.DRAGON) Severity.CRITICAL else Severity.HIGH,
            affectedPositions = listOf(agent.position, target.position)
        ))

        if (killed) {
            agent.kills++
            world.entities.remove(target)
            val eventType = if (target.type == EntityType.DRAGON) EventType.DRAGON_DEFEATED else EventType.COMBAT
            events.add(WorldEvent(
                tick = world.tick,
                eventType = eventType,
                description = "${agent.name} has slain the ${target.type.name.lowercase()}!",
                severity = Severity.HIGH,
                affectedPositions = listOf(target.position)
            ))
        }

        if (agent.status == AgentStatus.DEAD) {
            events.add(WorldEvent(
                tick = world.tick,
                eventType = EventType.AGENT_DIED,
                description = "${agent.name} has fallen in battle!",
                severity = Severity.CRITICAL,
                affectedPositions = listOf(agent.position)
            ))
        }

        return events
    }

    private fun resolveBuild(
        agent: com.vikingsai.engine.world.MutableAgent,
        action: AgentAction
    ): List<WorldEvent> {
        agent.currentAction = ActionType.BUILD
        agent.currentDirection = null
        // Deposit resources at village
        if (world.grid[agent.position.y][agent.position.x] == TerrainType.VILLAGE) {
            world.depositResources(agent)
            return listOf(WorldEvent(
                tick = world.tick,
                eventType = EventType.BUILDING_COMPLETE,
                description = "${agent.name} deposited resources at the village",
                severity = Severity.LOW,
                affectedPositions = listOf(agent.position)
            ))
        }
        return emptyList()
    }

    private fun resolvePatrol(
        agent: com.vikingsai.engine.world.MutableAgent,
        action: AgentAction
    ): List<WorldEvent> {
        // Patrol: move in a random direction
        val directions = listOf("north", "south", "east", "west")
        val dir = action.direction ?: directions.random()
        world.moveAgent(agent, dir)
        agent.currentAction = ActionType.PATROL
        agent.currentDirection = dir
        return emptyList()
    }

    private fun resolveFlee(
        agent: com.vikingsai.engine.world.MutableAgent,
        action: AgentAction
    ): List<WorldEvent> {
        // Flee: move away from nearest threat
        val threat = world.entities
            .filter { it.type == EntityType.WOLF || it.type == EntityType.DRAGON }
            .minByOrNull { manhattanDist(agent.position, it.position) }

        agent.currentAction = ActionType.FLEE

        if (threat != null) {
            agent.currentDirection = moveAwayFrom(agent, threat.position)
        } else {
            val dir = action.direction ?: "south"
            world.moveAgent(agent, dir)
            agent.currentDirection = dir
        }
        return emptyList()
    }

    private fun resolveSpeak(
        agent: com.vikingsai.engine.world.MutableAgent,
        action: AgentAction
    ): List<WorldEvent> {
        agent.currentAction = ActionType.SPEAK
        agent.currentDirection = null
        return listOf(WorldEvent(
            tick = world.tick,
            eventType = EventType.AGENT_SPOKE,
            description = "${agent.name}: ${action.reasoning}",
            severity = Severity.LOW,
            affectedPositions = listOf(agent.position)
        ))
    }

    // --- Helpers ---

    private fun moveToward(agent: com.vikingsai.engine.world.MutableAgent, target: Position): String {
        val dx = target.x - agent.position.x
        val dy = target.y - agent.position.y
        val dir = if (Math.abs(dx) > Math.abs(dy)) {
            if (dx > 0) "east" else "west"
        } else {
            if (dy > 0) "south" else "north"
        }
        world.moveAgent(agent, dir)
        return dir
    }

    private fun moveAwayFrom(agent: com.vikingsai.engine.world.MutableAgent, threat: Position): String {
        val dx = agent.position.x - threat.x
        val dy = agent.position.y - threat.y
        val dir = if (Math.abs(dx) > Math.abs(dy)) {
            if (dx > 0) "east" else "west"
        } else {
            if (dy > 0) "south" else "north"
        }
        world.moveAgent(agent, dir)
        return dir
    }

    private fun manhattanDist(a: Position, b: Position): Int =
        Math.abs(a.x - b.x) + Math.abs(a.y - b.y)
}
