package com.vikingsai.engine.tick

import com.vikingsai.common.model.*
import com.vikingsai.engine.world.MutableAgent
import com.vikingsai.engine.world.MutableEntity
import com.vikingsai.engine.world.WorldManager
import org.slf4j.LoggerFactory

/**
 * Executes one tick-step of an agent's current task.
 * Tasks are multi-tick: the executor decides the low-level action
 * (move, gather, fight, etc.) mechanically each tick.
 *
 * Returns world events generated by this step, and whether the task is complete.
 */
class TaskExecutor(private val world: WorldManager) {

    private val log = LoggerFactory.getLogger(TaskExecutor::class.java)

    data class StepResult(
        val events: List<WorldEvent> = emptyList(),
        val taskComplete: Boolean = false
    )

    fun executeStep(agent: MutableAgent): StepResult {
        val task = agent.currentTask ?: return StepResult()
        if (agent.status == AgentStatus.DEAD) return StepResult(taskComplete = true)

        return when (task.taskType) {
            TaskType.GATHER -> executeGather(agent, task)
            TaskType.DEPOSIT -> executeDeposit(agent, task)
            TaskType.FIGHT -> executeFight(agent, task)
            TaskType.FLEE -> executeFlee(agent, task)
            TaskType.MOVE_TO -> executeMoveTo(agent, task)
            TaskType.IDLE -> executeIdle(agent)
        }
    }

    // --- GATHER: move to resource source, gather until full or depleted ---

    private fun executeGather(agent: MutableAgent, task: AgentTask): StepResult {
        // If inventory full enough, task complete — agent needs to deposit
        val invCount = agent.inventory.values.sum()
        if (invCount >= 6) {
            return StepResult(taskComplete = true)
        }

        // Find nearest matching resource source
        val source = findResourceSource(agent, task.targetResourceType)
        if (source == null) {
            // No resources of this type remain
            return StepResult(taskComplete = true)
        }

        // If adjacent (dist <= 1), gather
        if (manhattan(agent.position, source.position) <= 1) {
            agent.currentAction = ActionType.GATHER
            agent.currentDirection = null
            val gathered = world.tryGather(agent)
            if (gathered != null) {
                return StepResult(events = listOf(WorldEvent(
                    tick = world.tick,
                    eventType = EventType.RESOURCE_GATHERED,
                    description = "${agent.name} gathered ${gathered.name.lowercase()}",
                    severity = Severity.LOW,
                    affectedPositions = listOf(agent.position)
                )))
            }
            // Source might have depleted between finding and gathering — try next tick
            return StepResult()
        }

        // Move toward the resource source
        agent.currentAction = ActionType.MOVE
        agent.currentDirection = moveToward(agent, source.position)
        return StepResult()
    }

    // --- DEPOSIT: return to village and deposit resources ---

    private fun executeDeposit(agent: MutableAgent, task: AgentTask): StepResult {
        // If no inventory, task complete
        if (agent.inventory.isEmpty() || agent.inventory.values.sum() == 0) {
            return StepResult(taskComplete = true)
        }

        // If on village tile, deposit
        if (world.grid[agent.position.y][agent.position.x] == TerrainType.VILLAGE) {
            agent.currentAction = ActionType.BUILD
            agent.currentDirection = null
            world.depositResources(agent)
            return StepResult(
                events = listOf(WorldEvent(
                    tick = world.tick,
                    eventType = EventType.BUILDING_COMPLETE,
                    description = "${agent.name} deposited resources at the village",
                    severity = Severity.LOW,
                    affectedPositions = listOf(agent.position)
                )),
                taskComplete = true
            )
        }

        // Move toward village center
        val villageTile = findNearestTerrain(agent.position, TerrainType.VILLAGE)
            ?: Position(world.grid[0].size / 2, world.grid.size / 2)
        agent.currentAction = ActionType.MOVE
        agent.currentDirection = moveToward(agent, villageTile)
        return StepResult()
    }

    // --- FIGHT: move toward nearest threat and attack ---

    private fun executeFight(agent: MutableAgent, task: AgentTask): StepResult {
        val target = world.entities
            .filter { it.type == EntityType.WOLF || it.type == EntityType.DRAGON }
            .minByOrNull { manhattan(agent.position, it.position) }

        if (target == null) {
            // No threats remaining
            return StepResult(taskComplete = true)
        }

        agent.currentAction = ActionType.FIGHT

        // If adjacent, attack
        if (manhattan(agent.position, target.position) <= 1) {
            val killed = world.resolveCombat(agent, target)
            val events = mutableListOf<WorldEvent>()

            events.add(WorldEvent(
                tick = world.tick,
                eventType = EventType.COMBAT,
                description = "${agent.name} fights a ${target.type.name.lowercase()}! (HP: ${agent.health})",
                severity = if (target.type == EntityType.DRAGON) Severity.CRITICAL else Severity.HIGH,
                affectedPositions = listOf(agent.position, target.position)
            ))

            if (killed) {
                agent.kills++
                val eventType = if (target.type == EntityType.DRAGON) EventType.DRAGON_DEFEATED else EventType.COMBAT
                events.add(WorldEvent(
                    tick = world.tick,
                    eventType = eventType,
                    description = "${agent.name} has slain the ${target.type.name.lowercase()}!",
                    severity = Severity.HIGH,
                    affectedPositions = listOf(target.position)
                ))
                world.entities.remove(target)
            }

            if (agent.status == AgentStatus.DEAD) {
                events.add(WorldEvent(
                    tick = world.tick,
                    eventType = EventType.AGENT_DIED,
                    description = "${agent.name} has fallen in battle!",
                    severity = Severity.CRITICAL,
                    affectedPositions = listOf(agent.position)
                ))
                return StepResult(events = events, taskComplete = true)
            }

            // If we killed the target, task complete
            return StepResult(events = events, taskComplete = killed)
        }

        // Move toward threat
        agent.currentDirection = moveToward(agent, target.position)
        return StepResult()
    }

    // --- FLEE: move away from nearest threat toward village ---

    private fun executeFlee(agent: MutableAgent, task: AgentTask): StepResult {
        val threat = world.entities
            .filter { it.type == EntityType.WOLF || it.type == EntityType.DRAGON }
            .minByOrNull { manhattan(agent.position, it.position) }

        agent.currentAction = ActionType.FLEE

        if (threat == null || manhattan(agent.position, threat.position) > 10) {
            // Safe — task complete
            return StepResult(taskComplete = true)
        }

        agent.currentDirection = moveAwayFrom(agent, threat.position)
        return StepResult()
    }

    // --- MOVE_TO: move to a specific position ---

    private fun executeMoveTo(agent: MutableAgent, task: AgentTask): StepResult {
        val target = task.targetPosition ?: return StepResult(taskComplete = true)

        if (agent.position == target) {
            return StepResult(taskComplete = true)
        }

        agent.currentAction = ActionType.MOVE
        agent.currentDirection = moveToward(agent, target)
        return StepResult()
    }

    // --- IDLE: rest for one tick ---

    private fun executeIdle(agent: MutableAgent): StepResult {
        agent.currentAction = ActionType.IDLE
        agent.currentDirection = null
        return StepResult(taskComplete = true)
    }

    // --- Movement helpers (with fallback on blocked) ---

    private fun moveToward(agent: MutableAgent, target: Position): String {
        val dx = target.x - agent.position.x
        val dy = target.y - agent.position.y

        val primary = if (Math.abs(dx) >= Math.abs(dy)) {
            if (dx > 0) "east" else if (dx < 0) "west" else null
        } else {
            if (dy > 0) "south" else if (dy < 0) "north" else null
        }
        val secondary = if (Math.abs(dx) >= Math.abs(dy)) {
            if (dy > 0) "south" else if (dy < 0) "north" else null
        } else {
            if (dx > 0) "east" else if (dx < 0) "west" else null
        }

        if (primary != null && world.moveAgent(agent, primary)) return primary
        if (secondary != null && world.moveAgent(agent, secondary)) return secondary
        for (dir in listOf("north", "south", "east", "west")) {
            if (world.moveAgent(agent, dir)) return dir
        }
        return primary ?: "north"
    }

    private fun moveAwayFrom(agent: MutableAgent, threat: Position): String {
        val dx = agent.position.x - threat.x
        val dy = agent.position.y - threat.y

        val primary = if (Math.abs(dx) >= Math.abs(dy)) {
            if (dx > 0) "east" else if (dx < 0) "west" else null
        } else {
            if (dy > 0) "south" else if (dy < 0) "north" else null
        }
        val secondary = if (Math.abs(dx) >= Math.abs(dy)) {
            if (dy > 0) "south" else if (dy < 0) "north" else null
        } else {
            if (dx > 0) "east" else if (dx < 0) "west" else null
        }

        if (primary != null && world.moveAgent(agent, primary)) return primary
        if (secondary != null && world.moveAgent(agent, secondary)) return secondary
        for (dir in listOf("north", "south", "east", "west")) {
            if (world.moveAgent(agent, dir)) return dir
        }
        return primary ?: "south"
    }

    // --- Resource/terrain helpers ---

    private fun findResourceSource(agent: MutableAgent, resourceType: ResourceType?): MutableEntity? {
        return world.entities
            .filter { it.type == EntityType.RESOURCE_NODE && it.health > 0 }
            .filter { resourceType == null || matchesResourceType(it, resourceType) }
            .minByOrNull { manhattan(agent.position, it.position) }
    }

    private fun matchesResourceType(entity: MutableEntity, resourceType: ResourceType): Boolean {
        return when (entity.subtype) {
            "tree" -> resourceType == ResourceType.TIMBER
            "mine" -> resourceType == ResourceType.IRON
            "fishing_spot" -> resourceType == ResourceType.FISH
            "hunting_ground" -> resourceType == ResourceType.FURS
            else -> false
        }
    }

    private fun findNearestTerrain(from: Position, terrain: TerrainType): Position? {
        var best: Position? = null
        var bestDist = Int.MAX_VALUE
        for (y in world.grid.indices) {
            for (x in world.grid[y].indices) {
                if (world.grid[y][x] == terrain) {
                    val d = manhattan(from, Position(x, y))
                    if (d < bestDist) { bestDist = d; best = Position(x, y) }
                }
            }
        }
        return best
    }

    private fun manhattan(a: Position, b: Position): Int =
        Math.abs(a.x - b.x) + Math.abs(a.y - b.y)
}
